# SPDX-License-Identifier: GPL-2.0-or-later
# Every case must reject before opening IPC, never fail later at an invalid path.
if(NOT DEFINED EXECUTABLE OR NOT EXISTS "${EXECUTABLE}")
  message(FATAL_ERROR "Built synthetic executable required")
endif()
foreach(case IN ITEMS zero unknown unbounded short_predecessor short_successor
    long no_path wrong_fps wrong_delay wrong_width wrong_height duplicate)
  set(arguments --path /avsync-invalid-test/never-open.ipc --duration 18)
  set(fixture 1)
  set(expected "Restart fixture requires role 1|2, explicit path, 640x360/60, 2000 ms delay, and finite duration 8..90 (predecessor) or 16..90 (successor)\n")
  if(case STREQUAL "zero")
    set(fixture 0)
  elseif(case STREQUAL "unknown")
    set(fixture 3)
  elseif(case STREQUAL "unbounded")
    list(APPEND arguments --duration 0)
  elseif(case STREQUAL "short_predecessor")
    list(APPEND arguments --duration 7)
  elseif(case STREQUAL "short_successor")
    set(fixture 2)
    list(APPEND arguments --duration 15)
  elseif(case STREQUAL "long")
    list(APPEND arguments --duration 91)
  elseif(case STREQUAL "no_path")
    set(arguments --duration 18)
  elseif(case STREQUAL "wrong_fps")
    list(APPEND arguments --fps 30)
  elseif(case STREQUAL "wrong_delay")
    list(APPEND arguments --delay-ms 0)
  elseif(case STREQUAL "wrong_width")
    list(APPEND arguments --width 1280)
  elseif(case STREQUAL "wrong_height")
    list(APPEND arguments --height 720)
  elseif(case STREQUAL "duplicate")
    list(APPEND arguments --restart-fixture 1)
    set(expected "Duplicate restart fixture\n")
  endif()
  list(APPEND arguments --restart-fixture "${fixture}")
  execute_process(COMMAND "${EXECUTABLE}" ${arguments} TIMEOUT 3
    RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT code STREQUAL "2" OR NOT out STREQUAL "" OR NOT err STREQUAL expected)
    message(FATAL_ERROR "Case ${case} did not fail with exact argument-only diagnostic")
  endif()
endforeach()
